//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt20
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_цен
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Справочник_цен()
        {
            this.Накладная_на_поступление = new HashSet<Накладная_на_поступление>();
            this.Требование_на_выдачу = new HashSet<Требование_на_выдачу>();
        }
    
        public int Код_детали { get; set; }
        public string Наименование_детали { get; set; }
        public double Цена { get; set; }
    
        public virtual Склад Склад { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Накладная_на_поступление> Накладная_на_поступление { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Требование_на_выдачу> Требование_на_выдачу { get; set; }
    }
}
